#!/bin/sh
# This file is generated by Flutter. DO NOT EDIT.
# This script forwards to the Flutter tool, which handles all environment
# configuration and then launches the application.

set -e

# Get the directory of this script
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Run the Flutter tool with the appropriate command
exec flutter "$@"
